big rewrite

diff --git a/buildenv/buildpkg b/buildenv/buildpkg
--- a/buildenv/buildpkg
+++ b/buildenv/buildpkg
@@ -1,46 +1,147 @@
 #!/bin/bash
-set -x
 set -e
 
-PKG="$1"
-REPO="$2"
-FORCE="$3"
 
-SAY="/tools/say"
-DIE="/tools/die"
+# =====
+say() {
+	tput bold
+	tput setaf 3
+	echo "----- $@"
+	tput sgr0
+}
 
-[ -d "/packages/$PKG" ] || $DIE "===== Required existent package in PKG argument ====="
+die() {
+	tput bold
+	tput setaf 1
+	echo "----- $@"
+	tput sgr0
+	exit 1
+}
 
-find /build -mindepth 1 -delete
-cp -r "/packages/$PKG"/* /build
-cd /build
+load_pkgbuild_info() {
+	local pkgbuild_path="$1"
+	source <( \
+		source "$pkgbuild_path" \
+		; [ -z "$epoch" ] || epoch_prefix="$epoch:" \
+		; deps=("${depends[@]}" "${makedepends[@]}") \
+		; printf %s\\n \
+			"_RET_VERSION=\"$epoch_prefix$pkgver-$pkgrel\"" \
+			"_RET_DEPS=\"${deps[*]}\"" \
+	)
+	[ -n "$_RET_VERSION" ] || die "Missing or incorrect PKGBUILD"
+}
 
-. PKGBUILD
-
-[ -z "$epoch" ] || epoch_prefix="$epoch:"
-NEW_VERSION="$epoch_prefix$pkgver-$pkgrel"
-OLD_VERSION=$(cat "/repo/latest/$PKG" 2>/dev/null || true)
-
-if [ "$NEW_VERSION" != "$OLD_VERSION" -o -n "$FORCE" ]; then
-	if [ "$NEW_VERSION" != "$OLD_VERSION" ]; then
-		$SAY "===== Building package $PKG ($OLD_VERSION -> $NEW_VERSION) ====="
-	else
-		$SAY "===== Building package $PKG (forced) ====="
+append_repo() {
+	local repo_name="$1"
+	local repo_dir="$2"
+	if [ -f "$repo_dir/$repo_name.db.tar.gz" ]; then
+		say "Appending repo $repo_name to /etc/pacman.conf ..."
+		cat <<-EOF>>/etc/pacman.conf
+			[$repo_name]
+			Server = file://$repo_dir
+			SigLevel = Required DatabaseOptional
+			EOF
 	fi
+}
 
-	if [ -f "/repo/$REPO.db.tar.gz" ]; then
-		echo -e "[$REPO]\nServer = file:///repo\nSigLevel = Required DatabaseOptional" >> /etc/pacman.conf
-	fi
+get_latest_version() {
+	local repo_dir="$1"
+	local pkg_name="$2"
+	_RET_VERSION=$(cat "$repo_dir/latest/$pkg_name" 2>/dev/null || true)
+}
 
-	if [ ${#depends[@]} -ne 0 -o ${#makedepends[@]} -ne 0 ]; then
+prepare_build_dir() {
+	local pkg_dir="$1"
+	local build_dir="$2"
+	say "Preparing build directory ..."
+	[ -d "$build_dir" ] || die "Missing build dir" $build_dir
+	find "$build_dir" -mindepth 1 -delete
+	cp "$pkg_dir"/* "$build_dir"
+}
+
+install_deps() {
+	local deps="$1"
+	if [ -n "$deps" ]; then
+		say "Installing dependencies ..."
 		pacman --noconfirm -Syy
-		pacman --needed --noconfirm -S ${depends[@]} ${makedepends[@]}
+		pacman --noconfirm --needed -S $deps
+	fi
+}
+
+build() {
+	local build_dir="$1"
+	pushd "$build_dir" >/dev/null
+	say "Building package ..."
+	sudo -u alarm makepkg
+	say "Signing package(s) ..."
+	ls *.pkg.tar.xz | sudo -u alarm xargs -n1 -L1 bash -c "gpg \
+			--verbose \
+			--pinentry-mode loopback \
+			--local-user $REPO_KEY \
+			--detach-sign \
+			--use-agent \
+			--no-autostart \
+			\$0 \
+		|| exit 255"
+	popd >/dev/null
+}
+
+place_to_repo() {
+	local build_dir="$1"
+	local pkg_name="$2"
+	local version="$3"
+	local repo_name="$4"
+	local repo_dir="$5"
+	say "Placing package(s) to repo ..."
+	cp "$build_dir"/*.pkg.tar.xz{,.sig} "$repo_dir"
+	pushd "$repo_dir" >/dev/null
+	repo-add --new "$repo_name.db.tar.gz" *.pkg.tar.xz
+	mkdir -p latest
+	echo "$version" > latest/$pkg_name
+	popd >/dev/null
+}
+
+
+# ===== Main =====
+main() {
+	local pkg_name="$1"; [ -n "$pkg_name" ] || die "Missing package name"
+	local force="$2"
+	local norepo="$3"
+
+	[ -n "$REPO_NAME" ] || die "Missing REPO_NAME variable"
+	[ -n "$REPO_KEY" ] || die "Missing REPO_KEY variable"
+	[ -n "$REPO_DIR" ] || die "Missing REPO_DIR variable"
+	[ -n "$BUILD_DIR" ] || die "Missing BUILD_DIR variable"
+	[ -n "$PACKAGES_DIR" ] || die "Missing PACKAGES_DIR variable"
+
+	# =====
+
+	load_pkgbuild_info "$PACKAGES_DIR/$pkg_name/PKGBUILD"
+	local version="$_RET_VERSION"; unset _RET_VERSION
+	local deps="$_RET_DEPS"; unset _RET_DEPS
+
+	get_latest_version "$REPO_DIR" "$pkg_name"
+	local old_version="$_RET_VERSION"; unset _RET_VERSION
+
+	if [ "$version" != "$old_version" ]; then
+		say "Found new $pkg_name (${old_version-<none>} -> $version)"
+		local build=1
+	elif [ -n "$force" ]; then
+		say "Forced rebuild of $pkg_name"
+		local build=1
+	else
+		say "Passed $pkg_name"
+		return
 	fi
 
-	sudo -u alarm makepkg
+	if [ -n "$build" ]; then
+		append_repo "$REPO_NAME" "$REPO_DIR"
+		prepare_build_dir "$PACKAGES_DIR/$pkg_name" "$BUILD_DIR"
+		install_deps "$deps"
+		build "$BUILD_DIR"
+		[ -n "$norepo" ] || place_to_repo "$BUILD_DIR" "$pkg_name" "$version" "$REPO_NAME" "$REPO_DIR"
+		say "Done!"
+	fi
+}
 
-	sudo -u alarm bash -c "ls \"$PKG\"-*.pkg.tar.xz > done"
-	sudo -u alarm bash -c "echo \"$NEW_VERSION\" > version"
-
-	$SAY "===== Build $PKG complete ====="
-fi
+main "$1" "$2" "$3"
